# Generated by Django 3.0.8 on 2020-07-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_ID', models.IntegerField()),
                ('CODE_NUMBER', models.IntegerField()),
                ('CODE_DESCRIPTION', models.CharField(max_length=100)),
                ('DATE', models.DateField(null=True)),
                ('AGE', models.FloatField()),
                ('GENDER', models.IntegerField()),
                ('NOTES', models.CharField(max_length=900)),
                ('CURRENTRX', models.CharField(max_length=100)),
                ('DOSE', models.CharField(max_length=100)),
                ('FREQUENCY', models.CharField(max_length=100)),
            ],
        ),
    ]
